---
- hosts: app
  tasks:
    - name: Ensure package are installed
      apt:
        pkg: 
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        update_cache: true

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        package: docker-ce
        update_cache: true

    - name: Enable docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
