---
- hosts: monitoring
  roles:
    - cloudalchemy.prometheus
  vars_files:
    - "../vars/prometheus.yaml"
  vars:
    prometheus_skip_install: false
    prometheus_scrape_configs:
    - job_name: "prometheus"
      metrics_path: "{{ prometheus_metrics_path }}"
      static_configs:
        - targets:
            - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
    - job_name: "openstack"
      openstack_sd_configs:
      - role: 'instance'
        region: "{{ openstack_region }}"
        identity_endpoint: "{{ openstack_identity_endpoint }}"
        domain_name: "{{ openstack_domain_name }}"
        username: "{{ openstack_username }}"
        password: "{{ openstack_password }}"
        project_id: "{{ openstack_project_id }}"
        port: 9100
      relabel_configs:
        - source_labels: [__meta_openstack_instance_name]
          action: keep

- hosts: all
  roles:
    - node-exporter